Add polygon label placement options
fleaflet/flutter_map pull request #1225
Opened 2022-05-05 20:51 UTC by beroso

Saw [this PR](https://github.com/fleaflet/flutter_map/pull/1220) about centered labels for polygons today.

I think it can be useful to add an option to place the label using [Dart polylabel](https://github.com/beroso/dart_polylabel). It works well on both convex and concave polygons.

Example:

| Centroid (current approach)  | Polylabel |
| ------------- | ------------- |
| <img width="234" alt="Screen Shot 2022-05-05 at 17 44 31" src="https://user-images.githubusercontent.com/7874200/167022894-1133b581-fc94-4de7-83d4-0fe45b9ef71a.png"> | <img width="224" alt="Screen Shot 2022-05-05 at 17 44 07" src="https://user-images.githubusercontent.com/7874200/167022958-ecc1703a-af4d-4de8-a2d1-b0711e305d0e.png"> |

2022-05-06 21:35 UTC, JaffaKetchup commented
Thanks for your PR! I'll have a proper look tomorrow :)
Just for now though, I can see that the enumerable names might need changing though, as they are a bit confusing.

2022-05-07 12:14 UTC, JaffaKetchup requested changes
This is working great! I've commented below on something(s) that might need changing, but I'm open to suggestions :)

2022-05-07 12:14 UTC, JaffaKetchup commented on lib/src/layer/label.dart
> +    PolygonLabelPlacement labelPlacement = PolygonLabelPlacement.centroid,
I think we should change the default to this new method, but that's just my opinion.

2022-05-07 12:14 UTC, JaffaKetchup commented on lib/src/layer/polygon_layer.dart
> +}
I also think we might need to rename these options to make them clearer to other people. Perhaps:

```suggestion
enum PolygonLabelPlacement {
  squareCenter,
  polyCenter,
}
```

2022-05-08 08:16 UTC, ibrierley approved these changes
I'm fine with this either way. It tests fine. It feels like each option in certain cases is preferable when I look at it visually, so no preference on which is default.

polylabel is maybe ambiguous as an parameter, but I guess it does what it says on the tin (uses whatever polylabel calculates, which could change and not be a center...). So no strong preference either way.

2022-05-08 08:20 UTC, JaffaKetchup commented on lib/src/layer/polygon_layer.dart
> +}
Ok, @ibrierley made a good point on this one, so I won't change it...

2022-05-08 08:24 UTC, JaffaKetchup approved these changes
LGTM

2022-05-08 08:25 UTC, merged