Fix TileLayer lag during fling/animated movement
fleaflet/flutter_map pull request #1247
Opened 2022-05-27 12:27 UTC by rorystephenson

When flinging or animating the moment of the map the TileLayer would lag behind which resulted in either jerkiness or other layers moving out of sync with the TileLayer depending on how fast the device is.

This PR should address that issue by moving the Tile translation calculation in to the builder rather than in a stream listener which called setState(). This means that translation is calculated during the build whilst updating/loading of tiles can still happen in the stream listener to prevent them from slowing down the build too much.

As part of these changes I heavily refactored the TileLayer code as it was difficult for me to follow.

2022-05-27 20:54 UTC, JaffaKetchup requested changes
Haven't tested/run anything, but this is all I could see from scrolling through the changes! You've really done a great job, thanks :)
All the suggestions are just slight optimisations and tidy up, and I'm open to discussion if you disagree with any of them.

2022-05-27 20:54 UTC, JaffaKetchup commented on lib/src/layer/tile_layer/tile_manager.dart
> +      }
Using nested if statements is generally worse for performance than a logic gate, especially where readability will not be affected that much.

```suggestion
      if (tile.coords.z != tileZoom && tile.loaded == null) {
        toRemove.add(entry.key);
      }
```

2022-05-27 20:54 UTC, JaffaKetchup commented on lib/src/layer/tile_layer/tile_layer_options.dart
> +  ///
Not sure if this was already here, but this empty line can be removed.

```suggestion
```

2022-05-27 20:54 UTC, JaffaKetchup commented on lib/src/layer/tile_layer/tile_layer_options.dart
> +  ///
Not sure if this was already here, but this empty line can be removed.

```suggestion
```

2022-05-27 20:54 UTC, JaffaKetchup commented on lib/src/layer/tile_layer/tile_layer.dart
> +  }
Removing unnecessary statements.

```suggestion
  State<StatefulWidget> createState() => _TileLayerState();
```

2022-05-27 20:54 UTC, JaffaKetchup commented on lib/src/layer/tile_layer/tile_layer.dart
> +  }
Removing unnecessary statements.

```suggestion
  CustomPoint getTileSize() => _tileSize;
```

2022-05-28 07:49 UTC, rorystephenson commented
Thanks @JaffaKetchup I've made those changes 👌 !

2022-05-28 07:52 UTC, JaffaKetchup commented
Thanks. I'll do a full test at some point today!

2022-05-28 10:40 UTC, ibrierley approved these changes
All looks good to me. Great stuff, and thanks for all the work done on this.

2022-05-28 11:03 UTC, JaffaKetchup commented
Testing now...

2022-05-28 11:14 UTC, JaffaKetchup approved these changes
LGTM. Many thanks once again!

2022-05-28 11:14 UTC, merged

2022-05-28 14:03 UTC, rorystephenson commented
Awesome I wasn't expecting it to get reviewed and merged so quick, thanks to both of you!