Implement `MapCamera` equality & `hashCode`
fleaflet/flutter_map pull request #1614
Opened 2023-08-14 20:02 UTC by jjoelson

This will ensure assertions like the one described in [this issue](https://github.com/fleaflet/flutter_map/issues/1613) work as intended.

2023-08-14 20:05 UTC, JaffaKetchup requested changes
Hi @jjoelson,

Thanks for resolving this yourself so quickly! I'll give it a test tomorrow based on your issue.

If you could just update your equality method to check for identity, as is good practise, that would be great :) I can do it if you don't have time.

2023-08-14 21:12 UTC, jjoelson commented on lib/src/map/camera/camera.dart
> +  bool operator ==(Object other) =>
Good catch! The PR is updated.

2023-08-14 21:14 UTC, JaffaKetchup commented on lib/src/map/camera/camera.dart
> +  bool operator ==(Object other) =>
Great, thanks! I'll test tomorrow.

2023-08-15 10:46 UTC, rorystephenson commented
Nice one @jjoelson! This would definitely be worth adding a test for.

2023-08-15 12:25 UTC, JaffaKetchup approved these changes
LGTM. Thanks for the contribution!

2023-08-15 12:25 UTC, merged