perf: add simplification caching to `PolygonLayer`
fleaflet/flutter_map pull request #1795
Opened 2024-01-13 12:31 UTC by JaffaKetchup

Reflected the same changes made to `PolylineLayer`. Also includes some minor performance enhancements and consistency changes to both.

2024-01-13 22:47 UTC, JaffaKetchup commented
> I assume .geojson.noformat is indicate that the file should not get treatend as a browsable file by tools or the user?
I'd suggest to gzip the geojson file. This shrinks the file size from 6.92MB down to 1.85MB, is build into dart:io and optimized for fast decoding.
Caveats: While browsers use gzip to speed up the fetching of websites, dart:html does not support gzip. Maybe we can still find a way around this limitation? (If it's no quick fix, don't worry about it since it can be changed later.)

I did consider compressing it, but I think the effort required to keep it working on web and quickly could offset the benefit. The '.noformat' part is just a 'random' string to prevent auto-formatters from formatting the JSON and bloating the file size with empty whitespace.

> The Polygon fill color currencly only works when simplification is disabled.

Good spot, will need to investigate that.

> The Polygon Layer screen showcased features like dotted borders, labels and so on before. While the polyline PR added simplification and culling to the existing page, this polygon PR removes the other polygons. Therefore could we showcase this feature inside a different screen?

I wasn't considering what I was doing fully when I removed the original polygons :D. I'll bring them back to where they were.

2024-01-15 18:48 UTC, JaffaKetchup commented
@josxha

> The Polygon fill color currencly only works when simplification is disabled.

Fixed, was an issue with the `copyWithNewPoints` method. Also fixed a related equality issue.

> The Polygon Layer screen showcased features like dotted borders, labels and so on before. While the polyline PR added simplification and culling to the existing page, this polygon PR removes the other polygons. Therefore could we showcase this feature inside a different screen?

I've split out both the polyline and polygon stress tests into their own page, grouped them with the Many Markers/Circles pages, redesigned those last two for consistency, and added the `PerformanceOverlay` widget.

2024-01-15 20:32 UTC, josxha requested changes
Good pull request! I only found one small thing that could be changed.

2024-01-15 20:32 UTC, josxha commented on example/lib/pages/many_circles.dart
>  const maxCirclesCount = 20000;
Use `maxCirclesCount` as max value for the slider.

2024-01-15 20:46 UTC, josxha approved these changes
lgtm

2024-01-15 20:49 UTC, merged