Add BlendMode src like in Polygons to make overlapping circles possible
fleaflet/flutter_map pull request #1869
Opened 2024-04-11 20:54 UTC by Y0ngg4n

Currently overlapping Polygons are adding up in stroke color. To fix this it adds the BlendMode.src to all so this should not happen anymore.
Before:
https://discord.com/channels/951867686378409984/1020066104204345404/threads/1225458561409220711
https://media.discordapp.net/attachments/1225458561409220711/1225458561627328624/image.png?ex=662a6eb9&is=6617f9b9&hm=5eaad014affff9afd5b6c9444f3aa1463c1bcbe773cd6bdc0ef204c5ee27f120&=&format=webp&quality=lossless&width=735&height=605

2024-04-12 00:01 UTC, mootw reviewed
do you have an example after picture or some code to test with? Also any particular reason to hard code the BlendMode vs pass it in as a parameter to the layer? Thanks for your contribution!

2024-04-12 09:36 UTC, Y0ngg4n commented
@mootw i could not test it because of dependency hell. But it uses the same blend mode as in the polygons so the behaviour should be the same.

2024-04-17 06:19 UTC, Alexays commented on lib/src/layer/circle_layer/painter.dart
> +        radiusPaint.blendMode = BlendMode.src;
You should move it to first assignment (paintPoint) to avoid useless re-assignment.

2024-04-17 06:19 UTC, Alexays commented on lib/src/layer/circle_layer/painter.dart
> +        radiusPaint.blendMode = BlendMode.src;
You can remove it if previous comment resolved.

2024-04-17 12:07 UTC, JaffaKetchup requested changes
Hey @Y0ngg4n, thanks for this so far!

Some changes do need to be made before we can merge this though:

 * We will require an example (or an update to the exisiting one), or at least some code to test on this occassion
 * It may also be a good idea to incorporate this into the polygon and polyline layers, although they use some more complex logic, so it may not work very performantly (may require more calls to `saveLayer`). This may be out of the scope of this PR?
 * And as said, it should become a property on both the `CircleLayer` and `CircleMarker`, with the same decision logic as other properties.

2024-09-12 17:21 UTC, JaffaKetchup commented
I'm going to close this for now. This is a good option to introduce to all the painting layers, but that needs a new PR.

2024-09-12 17:21 UTC, closed without merging