feat(perf): perform bbox culling prior to aggressive culling for polylines
fleaflet/flutter_map pull request #1993
Opened 2024-11-24 16:54 UTC by JaffaKetchup

Both types of culling are still performed after simplification.

It is expected that this will have the most effect on longer polylines that are not always within the viewport - for example, the user is zoomed into see part of one specific long polyline in a map with many. Whilst this does add more work, it avoids many iterations of a loop that would be useless. To minimize the expense of constructing the bounding box for the polylines, they are cached on the `Polyline` (the same as we do for `Polygon`s).
Note that the bbox culling still works in geographic space - this is what we do for polygons, and to avoid this, a new class would be needed to maintain efficiency, mixing `Bounds` and `DoublePoint`.

In the example stress test, with simplification set to 0.02 to increase stress on the culling, with the entire polyline off screen, it seems to reduce the load on the UI thread by about ~1-2ms.

Before:
![Screenshot 2024-11-24 164159](https://github.com/user-attachments/assets/d71db144-3824-429a-91f0-cb42b223125f)

After:
![Screenshot 2024-11-24 164354](https://github.com/user-attachments/assets/ad2dc62f-28e9-4e72-b530-12771b6695bd)

2024-11-24 18:09 UTC, mootw requested changes
is the bbox re-used for post-simplification culling or is that based on the simplified polygon?

2024-11-24 18:09 UTC, mootw commented on lib/src/layer/polyline_layer/polyline_layer.dart
> +      // where none of the line is visibles
```suggestion
      // when none of the lines are visible
```

small grammar fix

2024-11-24 18:38 UTC, JaffaKetchup commented
@fleaflet/maintainers

2024-11-24 20:59 UTC, JaffaKetchup commented
@mootw That's a good point. It is using the original shape not the simplified shape for the bounding box. However, it looks as though the polygon culling is also doing this.

2024-12-05 02:24 UTC, mootw approved these changes

2024-12-05 09:58 UTC, merged