bugfix: Prevent parent ListView widgets from snatching scrolling gestures
fleaflet/flutter_map pull request #717
Opened 2020-08-04 21:23 UTC by ritikmishra

Closes #253.

The issue was fixed by using a `GestureArenaTeam` in conjunction with extra gesture recognizers to ensure that the `ScalingGestureRecognizer` wins when we would expect it to do so.

2020-10-01 03:02 UTC, pqtrong17 commented
How to add it into my project? Do you have a example code?

2020-10-01 16:52 UTC, ritikmishra commented
If you want to use the fork, put the following in your pubspec.yaml

```
  flutter_map:
    git:
      url: https://github.com/ritikmishra/flutter_map.git
      ref: fix-listview-scrolling
```

2020-10-02 03:29 UTC, pqtrong17 commented
> If you want to use the fork, put the following in your pubspec.yaml
> 
> ```
>   flutter_map:
>     git:
>       url: https://github.com/ritikmishra/flutter_map.git
>       ref: fix-listview-scrolling
> ```

Okie. Thank you so much. Where did the file's location do this? I want to understand more about it

2020-10-02 03:33 UTC, pqtrong17 commented
It's worked for me. Can you explain how to it works?

2020-10-02 14:08 UTC, jakobkuehne commented
Sadly I can't use your git version because of flutter_map_marker_cluster.

`Because flutter_map_marker_cluster 0.2.9 depends on flutter_map ^0.10.1+1 and no versions of flutter_map_marker_cluster match >0.2.9 <0.3.0, flutter_map_marker_cluster ^0.2.9 requires flutter_map from hosted.`

Or am I doing something wrong? So far, I've never added a package directly from Git. But apart from the possibility to add your great customization via Git, this would be a very important feature and I can't understand why this is still not officially available in flutter_map...

> If you want to use the fork, put the following in your pubspec.yaml
> 
> ```
>   flutter_map:
>     git:
>       url: https://github.com/ritikmishra/flutter_map.git
>       ref: fix-listview-scrolling
> ```

2020-10-23 11:30 UTC, romainpurchla approved these changes
Work for me

2020-12-13 10:05 UTC, sm2017 commented
> It's worked for me. Can you explain how to it works?

@ritikmishra I'm interested to know that how it works

@johnpryan Please accept the PR

2020-12-13 20:31 UTC, ritikmishra commented
The mechanism through which Flutter recognizes gestures is called the [gesture arena](https://flutter.dev/docs/development/ui/advanced/gestures#gesture-disambiguation). Different gesture recognizers compete in the arena, and the **first** recognizer to accept the gesture, or the last recognizer remaining in the arena (i.e the other recognizers rejected the gesture), is responsible for handling it. 

Previously, the map was implicitly using 3 gesture recognizers through `GestureDetector`: `ScaleGestureRecognizer` (handling panning and zoom), `TapGestureRecognizer`, and `LongPressGestureRecognizer`. If the map is inside a widget that scrolls (i.e a `ListView`), a fourth gesture recognizer will be in the arena: either a `HorizontalDragGestureRecognizer` or a `VerticalDragGestureRecognizer` depending on the direction that it scrolls.

The problem was caused by the `ScaleGestureRecognizer` taking too long to accept the gesture, resulting in the `HorizontalDragGestureRecognizer`/`VerticalDragGestureRecognizer` winning in the gesture arena.

The solution was to use a [`GestureArenaTeam`](https://api.flutter.dev/flutter/gestures/GestureArenaTeam-class.html) to utilize a new `HorizontalDragGestureRecognizer` and a new `VerticalDragGestureRecognizer` to help the original `ScaleGestureRecognizer` win faster. A `GestureArenaTeam` has a captain and members -- whenever any gesture recognizer in the team accepts the gesture, the captain is put in charge of handling it. This way, a user can pan the map when it is inside a `ListView`/other scrollable widget.

2020-12-14 07:56 UTC, sm2017 commented
@ritikmishra as the PR is not merged, is there alternative solution , for example wrapping map with another widget?

2020-12-14 14:59 UTC, ritikmishra commented
I couldn't find a workaround, which is why I made this PR. If you can find some way to stop the ListView from being so greedy in the gesture arena & ensure that the pointer events from gestures that don't go to the ListView _do_ go to the FlutterMap, that should fix the problem.

2021-01-27 09:56 UTC, gsimko commented
@johnpryan can you please take a look?

2021-03-18 09:18 UTC, kengu commented
@ritikmishra Can you resolve the conflict and update this PR? I can review it when this is done.

2021-03-19 15:53 UTC, ritikmishra commented
@kengu i have resolved the conflict

2021-03-19 17:49 UTC, kengu requested changes

2021-03-19 17:49 UTC, kengu commented on lib/src/map/flutter_map_state.dart
> +              child: scaleGestureDetector(
If I understand this correctly @ritikmishra, the TeamGestureRecognizer will always ensure that flutter_map takes precedence over ListView scoll? I don't think we can conclude that this is the only behaviour user expect. I think we need to make this behavior configurable, just as it is for [scollables](https://api.flutter.dev/flutter/widgets/Scrollable-class.html) in general. I think we should add something similar (or equal) to [scrollPhysics](https://api.flutter.dev/flutter/widgets/ScrollPhysics-class.html) to MapOptions constructor.

@johnpryan? What do you think?

2021-05-20 16:47 UTC, BenBitDesign commented
Hi guys

I think @kengu makes a good point to make this configurable.

Is anyone looking into this?

2021-09-03 11:06 UTC, kengu commented
Closing, fixed by #994.

2021-09-03 11:06 UTC, closed without merging