Fix for Zoom-value outside min/maxZoom when changing BaseMap
fleaflet/flutter_map pull request #837
Opened 2021-03-08 19:27 UTC by Anders55

The fix will iterate through the current tiles and check if any of them are outside the minZoom and maxZoom-values of the new BaseMap-layer. If so, it will stop flutter_map from trying to replace old tiles with the corresponding tiles from the new BaseMap.

2021-03-08 22:25 UTC, Anders55 commented
Issue description with STR here: https://github.com/fleaflet/flutter_map/issues/836

2021-03-09 07:15 UTC, kengu commented
@johnpryan / @maRci002 - builds are consistently breaking and PR #810 fixes this.

2021-03-09 07:25 UTC, kengu requested changes

2021-03-09 07:25 UTC, kengu commented on lib/src/layer/tile_layer.dart
> +    var maxTileZoomValue = 1.0;
if `reloadTiles == true` already, this section is unnecessary. Should be moved to `if(!reloadTiles) {...` on line 451

2021-03-16 15:29 UTC, kengu commented
@Anders55 PR #810 fixes the unit-test that fails. You should pull master and merge/rebase it into this PR. This will resolve the travis-build.

2021-03-16 22:37 UTC, kengu approved these changes

2021-03-17 07:39 UTC, merged